cloud:
  aws:
    credentials:
      access-key: AKIAQSIZ44Y5I7XFIXNZ
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: logging-microservice-storage


